language: shell

env:
  global:
   - var_3=oookkk
   - secure: "N5R+UT78aNVTsDejKbGmOmD0uN+M64VDhbPXd9cU5/EtjCIt3iopmhQeWadBKRHYL7dZOZGBNd7n6ng2dyGgkpXmPI3oa/9+B+LzW5b+IIFkvueKFYNSrhR4JSpT8o2JxkKGDE/qYcFSov0X4cH6SvHv0ro/2JTfKwshtWkRwP3azwVQr5LxMb86xI4gkiPT/44bB0Siku5ihSBRE+2WYaBdq207IHnQ4dIVjcB9tAfEUlRpVAS5Ihdno+iOoRbO0GIX8X44eYYkdOTHnX/7qutpmNtB29zzCYHUG+2eIPC+qIBiu+YgPP2Dp/UE7IEfILYfdlhNYX2fORfDvwK1NIyqJjotW5qwu6RzOTLjm8XtltxEBvqHdG04frr+YjfoFDHIoieBhkfDw2xTSLv70EZ7AcxgFGwjcyy4dEHmhLjtuhaJCMyxnAcNwKQk5JqqTbM+uGfv6zxRJTpbC3W71r6ryfv4KSM0Js1t5A3YOKiSt7LqBIZSe9mNAgIYRzbQjbPHBpPp9KEgskP9PT4fAf195fb0FE5f+Iu7XrsB3minPhmu56w6zToqWgZ3U808YUI8q4LVHXwrw3MV+0u6UbzaWYFqtTINAzKetQsqIRDVR79kJETgdMWEDw27XAayiFrBkcrchMgj7czm522UTxn4XUFm14w3EOulblfvBkg="
   - secure: "sr0zt8FaBV2YR5ZfF9DPXP+D0LRhEyzgkQcshNFKNXss7iZ61rpXbjRdxdeLCkOe18v5geLmUUwa5j+7Gzdr/IUPpSglimWdueK6MJNpqnJ+T7lST/lC5OYA49TKogNjlBxKltJpyOQfivfvIBeik78VBq19HJuOyNMef8GfApcRqhMs0HYleXL0oTUX++VmeGiyYvcWh6sBlZ69B34A3IHcwAXZtPk69x2908bCXYP2c8jpVWhcqp8sXQFbu4GkUvYbjrGpsa4ZZ3VAxXlg4L8DJraBFGMYkBKTGND4DyCf0lzniBvau6z3e4lqYNlMNag9RWNlidc+axuX2k94VJ0ojGn5+I4d49sO/0FgnMhAQ9rLBYyb6Kqg9G9DcsupVVTk0BDNCWbGtuH1QPA12DV/k1q2CzWU6QtFF7QQAcuJJX45ikdtCmyDGVTa0+6sSe+Rp9wBEFYBdBod0WkuwcaAhnWpt+3ESJvHU1IdYusHoxiuGfz8JeN5WOaXY/N3579vJ3V8aTbXEeKYOUhvV1E5qe2mL+5WRrA5wy5C9xRkooR2ZI1jwyETgVS8jbL+2Vra+A8uftF4NWHb1fuw/UMLg6bL5/Sv4Jl8sTmDJj9woC8pvG+s3PrZeDXXnOU9+nKghgPG1QfB/lDbhV6pDbwJBpe9ysLSFy9J/Lb5sXo="
   - var_2=ookk
   - var_4=ookk4
jobs:

  include:

  - stage: Deploy application to AWS ...

    script:

      - echo Deployment starts ...
      - echo $test_var
      - echo $var_1
      - echo $var_2
      - echo $var_3
      - echo $var_4





notifications:

  slack:

    on_pull_requests: true

    rooms:
     - juwai:fbVrH3u9xkfC95YsIFFsCcbO

    on_success: always # default: always

    on_failure: always # default: always
